blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/c/projects/frontend/34
    about: General questions about dashboards / Všeobecné otázky o dashboardoch
